import streamlit as st
import pandas as pd
import joblib
import numpy as np
from fpdf import FPDF
import base64
import os # Import os for path joining

# Define multiple possible paths for the model file
POSSIBLE_PATHS = [
    'concrete_strength_model.pkl',
    '/content/drive/Othercomputers/VIKASH HP/Documents/GitHub/Concrete-Strength-AI/concrete_strength_model.pkl'
]

# 1. Load the trained AI model and scaler using path redundancy
model_components = None
for path in POSSIBLE_PATHS:
    if os.path.exists(path):
        try:
            with open(path, 'rb') as file:
                model_components = joblib.load(file)
            st.success(f"Model and scaler loaded successfully from {path}")
            break
        except Exception as e:
            st.warning(f"Error loading model from {path}: {e}")
            continue

if model_components is None:
    st.error("Error: Could not find 'concrete_strength_model.pkl' in local directory or Drive path.")
    st.stop()

model = model_components['model']
scaler = model_components['scaler']

# 2. Page Configuration & Custom UI Styling
st.set_page_config(
    page_title="Concrete AI Pro | BCE Bhagalpur",
    page_icon="🏗️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for Adaptive Light/Dark Theme Look
st.markdown("""
    <style>
    :root {
        --header-bg: rgb(30, 58, 138);
        --card-bg: rgba(255, 255, 255, 0.7);
        --text-color: rgb(30, 58, 138);
        --accent-gradient: linear-gradient(90deg, rgb(30, 58, 138) 0%, rgb(59, 130, 246) 100%);
    }

    @media (prefers-color-scheme: dark) {
        :root {
            --header-bg: #0f172a;
            --card-bg: rgba(30, 41, 59, 0.7);
            --text-color: #60a5fa;
            --accent-gradient: linear-gradient(90deg, rgb(59, 130, 246) 0%, rgb(37, 99, 235) 100%);
        }
    }

    header[data-testid="stHeader"] { background: rgba(0,0,0,0); }
    .stAppDeployButton { display: none !important; }
    #MainMenu { display: none !important; }
    footer { visibility: hidden; }

    .main-header {
        background-color: var(--header-bg);
        padding: 2rem;
        border-radius: 15px;
        color: white;
        text-align: center;
        margin-bottom: 2rem;
        box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.3);
    }

    .team-line { font-size: 0.9rem; opacity: 0.9; margin-top: 10px; font-style: italic; }

    div[data-testid="stVerticalBlock"] > div:has(div.stNumberInput) {
        background: var(--card-bg);
        backdrop-filter: blur(10px);
        padding: 20px;
        border-radius: 15px;
        border: 1px solid rgba(255, 255, 255, 0.1);
    }

    [data-testid="stMetricValue"] { font-size: 45px; color: var(--text-color); font-weight: 800; }

    .stButton>button {
        background: var(--accent-gradient);
        color: white;
        border: none;
        padding: 15px 30px;
        border-radius: 10px;
        font-weight: bold;
        transition: all 0.3s ease;
    }
    .stButton>button:hover {
        transform: translateY(-2px);
        box_shadow: 0 5px 15px rgba(59, 130, 246, 0.4);
        color: white;
    }
    </style>
    """, unsafe_allow_html=True)

# Function to generate PDF
def generate_pdf(inputs, prediction, student_info):
    pdf = FPDF()
    pdf.add_page()

    # Set blue theme color
    pdf.set_fill_color(30, 58, 138)
    pdf.rect(0, 0, 210, 40, 'F')

    # Title
    pdf.set_font("Arial", 'B', 24)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 20, "Concrete Strength Analysis Report", ln=True, align='C')
    pdf.set_font("Arial", 'I', 12)
    pdf.cell(0, 10, "Generated by Smart AI Predictor - BCE Bhagalpur", ln=True, align='C')

    pdf.ln(10)

    # Personnel Info Section
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "Project Personnel Information", ln=True)
    pdf.set_font("Arial", '', 12)
    pdf.cell(0, 7, f"Designed By: {student_info.get('name', 'N/A')} and its team {', '.join(team_members)}", ln=True)
    pdf.cell(0, 7, f"Group No 5 (Civil Engineering)", ln=True)
    pdf.cell(0, 7, f"Under the Guidance of: Dr. Subodh Kumar Suman", ln=True)
    pdf.cell(0, 7, f"Institution: Bhagalpur College of Engineering,Bhagalpur", ln=True)

    pdf.ln(5)

    # Mix Design Table
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "Mix Design Parameters", ln=True)

    pdf.set_font("Arial", 'B', 12)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(100, 10, "Ingredient Component", 1, 0, 'L', True)
    pdf.cell(90, 10, "Quantity", 1, 1, 'C', True) # Changed unit to be general

    pdf.set_font("Arial", '', 12)
    # Corrected to iterate over inputs for PDF, including WC_Ratio
    for key, value in inputs.items():
        unit = "kg/m³"
        if key == "Age":
            unit = "Days"
        elif key == "WC_Ratio":
            unit = "" # No specific unit for ratio
        pdf.cell(100, 10, str(key), 1)
        pdf.cell(90, 10, f"{value:.2f} {unit}", 1, 1, 'C')

    pdf.ln(10)

    # Prediction Result Box
    pdf.set_draw_color(30, 58, 138)
    pdf.set_line_width(1)
    pdf.set_fill_color(230, 242, 255)
    pdf.rect(10, pdf.get_y(), 190, 30, 'DF')

    pdf.set_y(pdf.get_y() + 5)
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, f"Predicted Compressive Strength: {prediction:.2f} MPa", ln=True, align='C')
    pdf.set_font("Arial", 'I', 12)
    pdf.cell(0, 10, f"Model Prediction Accuracy: 94.79%", ln=True, align='C') # Updated accuracy to Gradient Boosting R2

    pdf.ln(10)
    pdf.set_font("Arial", 'I', 10)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 5, "Disclaimer: This report is generated using an optimized Gradient Boosting machine learning model trained on experimental data.", align='C')

    return bytes(pdf.output())

# 3. Sidebar - Profile & Project Info
student_info = {"name": "Vikash Kumar", "roll": "D23177", "inst": "BCE Bhagalpur"}
team_members = ["Ritika", "Sarfe", "Harish", "Rishikesh", "Sahil", "Astitva"]

with st.sidebar:
    st.image("https://img.icons8.com/fluency/96/concrete-mixer.png", width=80)
    st.title("Project Info")
    st.markdown("### 👥 Group 5")
    st.info(f"**Lead:** {student_info['name']}\n\n**Roll:** {student_info['roll']}")

    with st.expander("🤝 Team Members", expanded=True):
        for member in team_members:
            st.write(f"• {member}")

    st.divider()
    st.success("✅ Model: Online")
    st.caption("Bhagalpur College of Engineering")

# 4. Top Hero Section
st.markdown(f"""
    <div class="main-header">
        <h1>🏗️ Smart Concrete Mix Strength Predictor</h1>
        <p style="font-size: 1.2rem;">Advanced Machine Learning for Civil Engineering Design Optimization</p>
        <div class="team-line">
            <b>Developed By Team:</b> Vikash, Ritika, Sarfe, Harish, Rishikesh, Sahil, Astitva
        </div>
    </div>
    """, unsafe_allow_html=True)


# 5. Input Section
st.subheader("📋 Mix Design Parameters")
col1, col2 = st.columns(2, gap="large")

with col1:
    st.markdown("### 🧪 Binder Ingredients")
    cement = st.number_input("Cement (kg/m³)", value=300.0, step=10.0, min_value=0.01)
    water = st.number_input("Water (kg/m³)", value=150.0, step=5.0, min_value=0.01)
    slag = st.number_input("Blast Furnace Slag (kg/m³)", value=0.0, step=10.0, min_value=0.0)
    fly_ash = st.number_input("Fly Ash (kg/m³)", value=0.0, step=10.0, min_value=0.0)

with col2:
    st.markdown("### 🪨 Aggregates & Aging")
    sp = st.number_input("Superplasticizer (kg/m³)", value=0.0, step=0.5, min_value=0.0)
    coarse = st.number_input("Coarse Aggregate (kg/m³)", value=1000.0, step=50.0, min_value=0.01)
    fine = st.number_input("Fine Aggregate (kg/m³)", value=700.0, step=50.0, min_value=0.01)
    age = st.slider("Curing Age (Days)", min_value=1, max_value=365, value=28)

# PREPARE INPUT DICTIONARY
# Including WC_Ratio in the input_dict as it's an engineered feature used by the model
wc_ratio = water / cement if cement != 0 else 0
input_dict = {
    'Cement': cement,
    'Slag': slag,
    'FlyAsh': fly_ash,
    'Water': water,
    'SP': sp,
    'CoarseAgg': coarse,
    'FineAgg': fine,
    'Age': age,
    'WC_Ratio': wc_ratio
}

# Ensure the feature order matches the training data
feature_columns = ['Cement', 'Slag', 'FlyAsh', 'Water', 'SP', 'CoarseAgg', 'FineAgg', 'Age', 'WC_Ratio']
input_df = pd.DataFrame([input_dict], columns=feature_columns)

# 6. Prediction Area
st.write("---")
if st.button("🚀 EXECUTE PREDICTION ANALYSIS", use_container_width=True):
    # Scale the input features
    scaled_input_df = scaler.transform(input_df)

    # Prediction
    prediction = model.predict(scaled_input_df)[0]

    # Display Results in a Professional Layout
    res_col1, res_col2 = st.columns([1, 2])

    with res_col1:
        st.metric(label="Predicted Strength", value=f"{prediction:.2f} MPa")

    with res_col2:
        if prediction > 40:
            st.success("🌟 **High Strength Concrete (HSC)**")
            st.write("Ideal for pre-stressed structures, high-rise buildings, and heavy bridges.")
            st.balloons()
        elif prediction > 20:
            st.info("🏠 **Normal Strength Concrete (NSC)**")
            st.write("Suitable for general reinforced concrete structures and slabs.")
        else:
            st.warning("🧱 **Low Strength Concrete**")
            st.write("Recommended for non-structural masonry, filling, or plain concrete work.")

    # PDF Generation
    try:
        pdf_bytes = generate_pdf(input_dict, prediction, student_info)

        st.download_button(
            label="📥 Download Professional PDF Report",
            data=pdf_bytes,
            file_name=f"BCE_Mix_Report_{age}days.pdf",
            mime="application/pdf",
            use_container_width=True
        )
    except Exception as e:
        st.error(f"PDF Generation failed: {str(e)}")

# 8. Visual Analytics
if st.checkbox("Show Strength-Age Gain Estimation"):
    age_range = np.arange(1, 91)
    plot_data_rows = []
    for day in age_range:
        current_input_data = input_dict.copy()
        current_input_data['Age'] = day
        # Re-calculate WC_Ratio if cement changes with age (not typical, but good for consistency)
        current_input_data['WC_Ratio'] = current_input_data['Water'] / current_input_data['Cement'] if current_input_data['Cement'] != 0 else 0
        plot_data_rows.append(current_input_data)

    age_test_df = pd.DataFrame(plot_data_rows, columns=feature_columns) # Ensure correct columns
    scaled_age_test_df = scaler.transform(age_test_df) # Scale for prediction
    strength_curve = model.predict(scaled_age_test_df)

    chart_data = pd.DataFrame({'Age (Days)': age_range, 'Strength (MPa)': strength_curve})
    st.line_chart(chart_data.set_index('Age (Days)'))
    st.caption("Estimated strength gain profile for this specific mix design.")
