import streamlit as st
import pandas as pd
import pickle
import numpy as np
from fpdf import FPDF
import base64

# 1. Load the trained AI model (0.9074 Accuracy)
try:
    model = pickle.load(open('concrete_model.pkl', 'rb'))
except FileNotFoundError:
    st.error("Error: 'concrete_model.pkl' not found. Please ensure the model file is in the project folder.")

# 2. Page Configuration & Custom UI Styling
st.set_page_config(
    page_title="Concrete AI Pro | BCE Bhagalpur",
    page_icon="🏗️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for Adaptive Light/Dark Theme Look and hiding specific Toolbar buttons
st.markdown("""
    <style>
    /* Theme-aware variables */
    :root {
        --header-bg: #1e3a8a;
        --card-bg: rgba(255, 255, 255, 0.7);
        --text-color: #1e3a8a;
        --accent-gradient: linear-gradient(90deg, #1e3a8a 0%, #3b82f6 100%);
    }

    @media (prefers-color-scheme: dark) {
        :root {
            --header-bg: #0f172a;
            --card-bg: rgba(30, 41, 59, 0.7);
            --text-color: #60a5fa;
            --accent-gradient: linear-gradient(90deg, #3b82f6 0%, #2563eb 100%);
        }
    }

    /* HIDE TOP TOOLBAR BUTTONS */
    header[data-testid="stHeader"] {
        background: rgba(0,0,0,0);
        color: rgba(0,0,0,0);
    }
    [data-testid="stToolbar"] {
        display: show !important;
    }
    .stAppDeployButton {
        display: none !important;
    }
    #MainMenu {
        display: none !important;
    }
    footer {
        visibility: hidden;
    }

    /* Custom Header */
    .main-header {
        background-color: var(--header-bg);
        padding: 2rem;
        border-radius: 15px;
        color: white;
        text-align: center;
        margin-bottom: 2rem;
        box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.3);
    }
    
    .team-line {
        font-size: 0.9rem;
        opacity: 0.9;
        margin-top: 10px;
        font-style: italic;
    }
    
    /* Card-like containers for inputs */
    div[data-testid="stVerticalBlock"] > div:has(div.stNumberInput) {
        background: var(--card-bg);
        backdrop-filter: blur(10px);
        padding: 20px;
        border-radius: 15px;
        border: 1px solid rgba(255, 255, 255, 0.1);
    }
    
    /* Metric Styling */
    [data-testid="stMetricValue"] {
        font-size: 45px;
        color: var(--text-color);
        font-weight: 800;
    }
    
    /* Buttons */
    .stButton>button {
        background: var(--accent-gradient);
        color: white;
        border: none;
        padding: 15px 30px;
        border-radius: 10px;
        font-weight: bold;
        transition: all 0.3s ease;
    }
    .stButton>button:hover {
        transform: translateY(-2px);
        box-shadow: 0 5px 15px rgba(59, 130, 246, 0.4);
        color: white;
    }
    </style>
    """, unsafe_allow_html=True)

# Function to generate PDF
def generate_pdf(inputs, prediction, student_info):
    pdf = FPDF()
    pdf.add_page()
    
    # Set blue theme color
    pdf.set_fill_color(30, 58, 138) 
    pdf.rect(0, 0, 210, 40, 'F')
    
    # Title
    pdf.set_font("Arial", 'B', 24)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 20, "Concrete Strength Analysis Report", ln=True, align='C')
    pdf.set_font("Arial", 'I', 12)
    pdf.cell(0, 10, "Generated by Smart AI Predictor - BCE Bhagalpur", ln=True, align='C')
    
    pdf.ln(20)
    
    # Student Info Section
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "Project Personnel Information", ln=True)
    pdf.set_font("Arial", '', 12)
    pdf.cell(0, 7, f"Designed By: {student_info['name']}", ln=True)
    pdf.cell(0, 7, f"Roll No: {student_info['roll']}", ln=True)
    pdf.cell(0, 7, f"Reg No: {student_info['reg']}", ln=True)
    pdf.cell(0, 7, f"Institution: {student_info['inst']}", ln=True)
    
    pdf.ln(10)
    
    # Mix Design Table
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "Mix Design Parameters", ln=True)
    
    pdf.set_font("Arial", 'B', 12)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(100, 10, "Ingredient Component", 1, 0, 'L', True)
    pdf.cell(90, 10, "Quantity (kg/m3)", 1, 1, 'C', True)
    
    pdf.set_font("Arial", '', 12)
    for key, value in inputs.items():
        pdf.cell(100, 10, str(key), 1)
        pdf.cell(90, 10, f"{value:.2f}", 1, 1, 'C')
    
    pdf.ln(10)
    
    # Prediction Result Box
    pdf.set_draw_color(30, 58, 138)
    pdf.set_line_width(1)
    pdf.set_fill_color(230, 242, 255)
    pdf.rect(10, pdf.get_y(), 190, 30, 'DF')
    
    pdf.set_y(pdf.get_y() + 5)
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, f"Predicted Compressive Strength: {prediction:.2f} MPa", ln=True, align='C')
    pdf.set_font("Arial", 'I', 12)
    pdf.cell(0, 10, f"Model Prediction Accuracy: 94.66%", ln=True, align='C')
    
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 10)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 5, "Disclaimer: This report is generated using a Random Forest machine learning model trained on experimental data. Actual field results may vary based on environmental conditions and curing techniques.", align='C')
    
    # FIX: Convert bytearray to bytes for Streamlit compatibility
    return bytes(pdf.output())

# 3. Sidebar - Profile & Project Info
student_info = {
    "name": "Vikash Kumar",
    "roll": "D23177",
    "reg": "23101108906",
    "inst": "BCE Bhagalpur"
}

with st.sidebar:
    st.image("https://img.icons8.com/external-beshi-flat-kerismaker/48/external-Concrete-Mix-construction-beshi-flat-kerismaker.png", width=100)
    st.title("Project Details")
    st.markdown("---")
    st.markdown(f"""
    **🎓 Designed By:** **{student_info['name']}** **🆔 Roll No:** {student_info['roll']}  
    **📝 Reg No:** {student_info['reg']}  
    **🏛️ Institution:** {student_info['inst']}  
    **🔬 Algorithm:** Random Forest  
    **🎯 Accuracy:** 94.66%
    """)
    st.success("Model Status: Online")
    st.write("---")
    st.caption("Final Year Major Project 2026")

# 4. Top Hero Section
st.markdown(f"""
    <div class="main-header">
        <h1>🏗️ Smart Concrete Mix Strength Predictor</h1>
        <p style="font-size: 1.2rem;">Advanced Machine Learning for Civil Engineering Design Optimization</p>
        <div class="team-line">
            <b>Developed By Team:</b> Vikash, Ritika, Sarfe, Harish, Rishikesh, Sahil, Astitva
        </div>
    </div>
    """, unsafe_allow_html=True)

# 5. Input Section
st.subheader("📋 Mix Design Parameters")
col1, col2 = st.columns(2, gap="large")

with col1:
    st.markdown("### 🧪 Binder Ingredients")
    cement = st.number_input("Cement (kg/m³)", value=300.0, step=10.0, min_value=0.0)
    water = st.number_input("Water (kg/m³)", value=150.0, step=5.0, min_value=0.0)
    slag = st.number_input("Blast Furnace Slag (kg/m³)", value=0.0, step=10.0, min_value=0.0)
    fly_ash = st.number_input("Fly Ash (kg/m³)", value=0.0, step=10.0, min_value=0.0)

with col2:
    st.markdown("### 🪨 Aggregates & Aging")
    sp = st.number_input("Superplasticizer (kg/m³)", value=0.0, step=0.5, min_value=0.0)
    coarse = st.number_input("Coarse Aggregate (kg/m³)", value=1000.0, step=50.0, min_value=0.0)
    fine = st.number_input("Fine Aggregate (kg/m³)", value=700.0, step=50.0, min_value=0.0)
    age = st.slider("Curing Age (Days)", min_value=1, max_value=365, value=28)

# PREPARE INPUT DICTIONARY
input_dict = {
    'Cement': cement, 'Slag': slag, 'FlyAsh': fly_ash, 'Water': water,
    'SP': sp, 'CoarseAgg': coarse, 'FineAgg': fine, 'Age': age
}

# 6. Prediction Area
st.write("---")
if st.button("🚀 EXECUTE PREDICTION ANALYSIS", use_container_width=True):
    input_df = pd.DataFrame([input_dict])
    
    # Prediction
    prediction = model.predict(input_df)[0]
    
    # Display Results in a Professional Layout
    res_col1, res_col2 = st.columns([1, 2])
    
    with res_col1:
        st.metric(label="Predicted Strength", value=f"{prediction:.2f} MPa")
    
    with res_col2:
        if prediction > 40:
            st.success("🌟 **High Strength Concrete (HSC)**")
            st.write("Ideal for pre-stressed structures, high-rise buildings, and heavy bridges.")
            st.balloons()
        elif prediction > 20:
            st.info("🏠 **Normal Strength Concrete (NSC)**")
            st.write("Suitable for general reinforced concrete structures and slabs.")
        else:
            st.warning("🧱 **Low Strength Concrete**")
            st.write("Recommended for non-structural masonry, filling, or plain concrete work.")

    # PDF Generation
    try:
        pdf_bytes = generate_pdf(input_dict, prediction, student_info)
        
        st.download_button(
            label="📥 Download PDF Report",
            data=pdf_bytes,
            file_name=f"BCE_Mix_Report_{age}days.pdf",
            mime="application/pdf",
            use_container_width=True
        )
    except Exception as e:
        st.error(f"PDF Generation failed: {str(e)}")

# 8. Visual Analytics
if st.checkbox("Show Strength-Age Gain Estimation"):
    age_range = np.arange(1, 91)
    plot_data_rows = []
    for day in age_range:
        current_row = input_dict.copy()
        current_row['Age'] = day
        plot_data_rows.append(current_row)
        
    age_test_df = pd.DataFrame(plot_data_rows)
    strength_curve = model.predict(age_test_df)
    
    chart_data = pd.DataFrame({'Age (Days)': age_range, 'Strength (MPa)': strength_curve})
    st.line_chart(chart_data.set_index('Age (Days)'))
    st.caption("Estimated strength gain profile for this specific mix design.")


